# Generated by Django 4.1.7 on 2023-04-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NovoTenis',
            new_name='Tenis',
        ),
    ]
